// AIM - Show C++ compilers mangle the function names, while C compilers don't.

// When we compile this C file and use nm to analyze the symbols generated by
// the compiler, we see that the function name do_c_stuff is present.
//
// RUN : $ nm ccode.o
//
// 0000000000000000 T do_c_stuff
//
// This shows that the compiler doesn't mangle the function name and if we want
// to call this function from another programming language, we can call
// this function using the name 'do_c_stuff'.
//
// However, for C++ codes, we will see that the function names are mangled.
// Thus we need to use extern "C" to instruct the C++ compiler not to mangle
// the function name.
//
int do_c_stuff()
{
    return 0;
}
